In [1]:
%reset -f

In [2]:
folder_path = r"C:\Users\Heng2020\OneDrive\Python NLP\OutputData\Westworld S04E01"
script_path = r"C:\Users\Heng2020\OneDrive\Python NLP\OutputData\Westworld_S04E01_pd.xlsx"

In [3]:
import os
import random
import pandas as pd
from play_audio_file import play_audio_file, play_alarm_done
# import excel_toolkit as xt
import dataframe_short as ds
from pydub import AudioSegment
from pydub.playback import play

import whisper 

import ffmpeg

from pydub import AudioSegment
from pydub.playback import play

# Example usage

alarm_path = r"H:\D_Music\Sound Effect positive-logo-opener.mp3"
speed_factor = 0.5  # Play at 50% slower speed
################################ reload model(needs to be runed) ######################################
# spyder can't have model_base &  model_large: I have to reload everytime

In [4]:
def play_audio_slower(audio_path, speed_factor):
    # still not working
    # right now I use this to play audio because playsound sometimes have weird problem
    # TODO: Find way to play audio with slower speed without changing the file
    audio = AudioSegment.from_file(audio_path)
    
    # slowed_audio = audio.speedup(playback_speed=1/speed_factor)
    slow_audio = audio._spawn(audio.raw_data, overrides={"frame_rate": int(audio.frame_rate * speed_factor)})
    play(slow_audio)


def get_filename(folder_path,extension = "all"):
    # also include "folder"  case
# tested small
    if extension == "all":
        out_list = [ file for file in os.listdir(folder_path) ]

    elif isinstance(extension,str):
        extension_temp = [extension]

        out_list = []

        for file in os.listdir(folder_path):
            if "." in file:
                file_extension = file.split('.')[-1]
                for each_extention in extension_temp:
                    # support when it's ".csv" or only "csv"
                    if file_extension in each_extention:
                        out_list.append(file)
            elif extension == "folder":
                out_list.append(file)


    elif isinstance(extension,list):
        out_list = []
        for file in os.listdir(folder_path):

            if "." in file:
                file_extension = file.split('.')[-1]
                for each_extention in extension:
                    # support when it's ".csv" or only "csv"
                    if file_extension in each_extention:
                        out_list.append(file)

            elif "folder" in extension:
                out_list.append(file)

        return out_list

    else:
        print("Don't support this dataype for extension: please input only string or list")
        return False

    return out_list

In [5]:
# play_alarm_done()

In [6]:
model_base = whisper.load_model('base')
model_large = whisper.load_model('large')
play_alarm_done()
#------------------------------ reload model ------------------------------

# Read meta data

In [7]:
meta_data_path = r'C:\Users\Norat\OneDrive\D_Code\Python\Python NLP\NLP 01\NLP 01_AudioShuffle\excel_info_path\learn_German_audio_metadata.xlsm'
SHEET_NAME = 'A1'
meta_data_df = ds.read_excel(meta_data_path, sheet_name = SHEET_NAME)

COL_AUDIO_PATH = 'audio_path'
COL_SENTENCE = 'German'
COL_TRANSLATION = 'English'

In [8]:
meta_data_df.head()

,index,audio_path,German,English,is_skipped
0,1.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Morgen, Herr Müller, wie geht es Ihnen?","– Good morning, Mr. Müller, how are you?",False
1,2.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Morgen, Frau Schneider. Danke, gut! Un...","– Good morning, Ms. Schneider. Fine, thank you...",False
2,3.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Morgen, Herr Müller, wie geht es Ihnen?","– Good morning, Mr. Müller, how are you?",False
3,4.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Morgen, Frau Schneider. Danke, gut! Un...","– Good morning, Ms. Schneider. Fine, thank you...",False
4,5.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Tag, Frau Kamp.","– Good day, Ms. Kamp.",False

In [9]:
file_path = dict(zip(meta_data_df['index'], meta_data_df[COL_AUDIO_PATH]))
# file_path = get_filename(folder_path,[".mp3",".wav"])
# file_path.insert(0,None)
script = meta_data_df.copy()

# Select start and end Index

In [734]:
# 1190 onwards
start_inx = 1220

end_inx = 1225
# (Sep 13, 2025: 1225)

In [735]:
# 55 is too easy

skip_inx = [1065, 1067, 1068, 1071, 1076, 1081, 1084, 1091, 1103, 1106, 1117, 1120, 1121, 1122, 1124, 1126, 1130, 1131, 1134, 1137, 1140, 1144, 1149, 1158, 1159, 1161, 1169, 1170, 1176, 1178, 1182, 1190, 1191, 1193, 1197,1198, 1200, 1202, 1203, 1212, 1216, 1217, 1219, 1225, 1233, 1236, 1239, 1240, 1243, 1247, 1251, 1256, 1265, 1269, 1270, 1271, 1272, 1275, 1276, 1277, 1279, 1287, 1288, 1289, 1292, 1293, 1295, 1297, 1298, 1301, 1308, 1310, 1328, 1334, 1336, 1337, 1338, 1339, 1345, 1354, 1359, 1360, 1398, 1409, 1410, 1422, 1427, 1429, 1430, 1445, 1448, 1449, 1450, 1451, 1452, 1458, 1479, 1480, 1484, 1494, 1498, 1501, 1502, 1506, 1507, 1513, 1517, 1521, 1540, 1543, 1545, 1561, 1563, 1564, 1588, 1597, 1603, 1607, 1608, 1609, 1613, 1616, 1629, 1636, 1637, 1671, 1672, 1675, 1685, 1693, 1699, 1705, 1712, 1728, 1729, 1730, 1731, 1734, 1736, 1739, 1745, 1747, 1748, 1750, 1751, 1753, 1756, 1757, 1760, 1762, 1766, 1776, 1781, 1785, 1786, 1796, 1799, 1800, 1803, 1863, 1866, 1871, 1872]
easy = []

KEEP_INDEX = []
# KEEP_INDEX = [1206,1205, 1199,1204, 1207]
# [1221,1220]

# (2,'2-Jul-23')
# (6,'2-Jul-23')
# (10,'2-Jul-23')
# (13,'2-Jul-23')
# (18,'2-Jul-23')

# (31,'2-Aug-23')
# (36,'2-Aug-23')
# (38,'2-Aug-23')

# (46,'9-Jul-23')
# (66,'31-Jul-23')
# (67,'31-Jul-23')
# (73,'31-Jul-23')
# (75,'31-Jul-23')

In [736]:
mySeed = 30
random_inx_list =list(range(start_inx,end_inx+1))
random_inx_list = list( set([x for x in random_inx_list if x not in skip_inx] + KEEP_INDEX))
print(f"Allow index is from 0 to {len(random_inx_list)-1}")
random.seed(mySeed)
random.shuffle(random_inx_list)

Allow index is from 0 to 4

In [643]:
script.head()

,index,audio_path,German,English,is_skipped
0,1.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Morgen, Herr Müller, wie geht es Ihnen?","– Good morning, Mr. Müller, how are you?",False
1,2.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Morgen, Frau Schneider. Danke, gut! Un...","– Good morning, Ms. Schneider. Fine, thank you...",False
2,3.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Morgen, Herr Müller, wie geht es Ihnen?","– Good morning, Mr. Müller, how are you?",False
3,4.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Morgen, Frau Schneider. Danke, gut! Un...","– Good morning, Ms. Schneider. Fine, thank you...",False
4,5.0,C:\C_Video_Python\Learn German\Learn German wi...,"– Guten Tag, Frau Kamp.","– Good day, Ms. Kamp.",False

# Set up per audio

In [728]:
########################## run below recurrently ##################################
i = 4
chosen_inx = random_inx_list[i]
# chosen_inx = 137
print(f"Index: {chosen_inx}")
try:
    audio_path = file_path[chosen_inx]
except KeyError as e:
    raise ValueError(f"Please check if index: {random_inx_list[i]} exists in meta file(excel)")
speed_factor = 1
curr_audio = AudioSegment.from_file(file_path[chosen_inx]) 

target_sentence = script.loc[script['index'] == chosen_inx, COL_SENTENCE].values[0].replace('\r','')
translation = script.loc[script['index'] == chosen_inx, COL_TRANSLATION].values[0].replace('\r','')
# play_audio_slower(audio_path, speed_factor)

Index: 1224

# Audio

In [729]:
curr_audio

In [730]:
from IPython.display import display, Markdown

display(Markdown(f"""
<details>
  <summary>Show target sentence</summary>

<div style="font-size: 24px; line-height: 1.4;">{target_sentence}</div>
</details>

<details>
  <summary>Show translation</summary>

<div style="font-size: 24px; line-height: 1.4;">{translation}</div>
</details>
"""))

<details>
  <summary>Show target sentence</summary>

<div style="font-size: 24px; line-height: 1.4;">Aber am liebsten mache ich …</div>
</details>

<details>
  <summary>Show translation</summary>

<div style="font-size: 24px; line-height: 1.4;">But what I like to do most …</div>
</details>

# Translation to target

In [731]:
print(translation)

But what I like to do most …

In [732]:
curr_audio

In [733]:
display(Markdown(f"""
<details>
  <summary>Show transcribed text</summary>

<div style="font-size: 24px; line-height: 1.4;">{target_sentence}</div>
</details>
"""))

<details>
  <summary>Show transcribed text</summary>

<div style="font-size: 24px; line-height: 1.4;">Aber am liebsten mache ich …</div>
</details>