In [153]:
%reset -f

In [154]:
folder_path = r"C:\Users\Heng2020\OneDrive\Python NLP\OutputData\Westworld S04E01"
script_path = r"C:\Users\Heng2020\OneDrive\Python NLP\OutputData\Westworld_S04E01_pd.xlsx"

In [155]:
import os
import random
import pandas as pd
from play_audio_file import play_audio_file, play_alarm_done
# import excel_toolkit as xt
import dataframe_short as ds
from pydub import AudioSegment
from pydub.playback import play

import whisper 

import ffmpeg

from pydub import AudioSegment
from pydub.playback import play

# Example usage

alarm_path = r"H:\D_Music\Sound Effect positive-logo-opener.mp3"
speed_factor = 0.5  # Play at 50% slower speed
################################ reload model(needs to be runed) ######################################
# spyder can't have model_base &  model_large: I have to reload everytime

In [156]:
def play_audio_slower(audio_path, speed_factor):
    # still not working
    # right now I use this to play audio because playsound sometimes have weird problem
    # TODO: Find way to play audio with slower speed without changing the file
    audio = AudioSegment.from_file(audio_path)
    
    # slowed_audio = audio.speedup(playback_speed=1/speed_factor)
    slow_audio = audio._spawn(audio.raw_data, overrides={"frame_rate": int(audio.frame_rate * speed_factor)})
    play(slow_audio)


def get_filename(folder_path,extension = "all"):
    # also include "folder"  case
# tested small
    if extension == "all":
        out_list = [ file for file in os.listdir(folder_path) ]

    elif isinstance(extension,str):
        extension_temp = [extension]

        out_list = []

        for file in os.listdir(folder_path):
            if "." in file:
                file_extension = file.split('.')[-1]
                for each_extention in extension_temp:
                    # support when it's ".csv" or only "csv"
                    if file_extension in each_extention:
                        out_list.append(file)
            elif extension == "folder":
                out_list.append(file)


    elif isinstance(extension,list):
        out_list = []
        for file in os.listdir(folder_path):

            if "." in file:
                file_extension = file.split('.')[-1]
                for each_extention in extension:
                    # support when it's ".csv" or only "csv"
                    if file_extension in each_extention:
                        out_list.append(file)

            elif "folder" in extension:
                out_list.append(file)

        return out_list

    else:
        print("Don't support this dataype for extension: please input only string or list")
        return False

    return out_list

In [ ]:
# play_alarm_done()

In [14]:
model_base = whisper.load_model('base')
model_large = whisper.load_model('large')
play_alarm_done()
#------------------------------ reload model ------------------------------

# Read meta data

In [ ]:
meta_data_path = r'C:\Users\Norat\OneDrive\D_Code\Python\Python NLP\NLP 01\NLP 01_AudioShuffle\excel_info_path\learn_French_audio_metadata.xlsm'
SHEET_NAME = 'sheet1'

meta_data_df = ds.read_excel(meta_data_path, sheet_name = 'sheet1')

COL_AUDIO_PATH = 'audio_path'
COL_SENTENCE = 'French'
COL_TRANSLATION = 'English'

In [158]:
meta_data_df.head()

,index,audio_path,French,English,Topic,level
0,1.0,C:\C_Video_Python\Learn French\100 questions e...,"Aujourd'hui, j'ai envie\n de vous raconter que...",I want to tell you\r about something today.,None,None
1,2.0,C:\C_Video_Python\Learn French\100 questions e...,"Souvent, je prends des nouvelles de ma\r famil...",I often check up on my family\r by calling the...,None,None
2,3.0,C:\C_Video_Python\Learn French\100 questions e...,"Et depuis quelque temps, j'essaie de\r changer...","And for some time now, I've been trying\r to c...",None,None
3,4.0,C:\C_Video_Python\Learn French\100 questions e...,"Avant,\r si j'appelais mon frère ou mes cousins,","When I used to call\r my brother or my cousins,",None,None
4,5.0,C:\C_Video_Python\Learn French\100 questions e...,je leur demandais seulement :\r « Ça va ? ». O...,"I'd just ask them: ""Are\r you all right? Or,",None,None

In [182]:
file_path = dict(zip(meta_data_df['index'], meta_data_df[COL_AUDIO_PATH]))
# file_path = get_filename(folder_path,[".mp3",".wav"])
# file_path.insert(0,None)
script = meta_data_df.copy()

# Select start and end Index

In [160]:
start_inx = 250
end_inx = 260

In [161]:
# 55 is too easy

skip_inx = []
easy = []

# (2,'2-Jul-23')
# (6,'2-Jul-23')
# (10,'2-Jul-23')
# (13,'2-Jul-23')
# (18,'2-Jul-23')

# (31,'2-Aug-23')
# (36,'2-Aug-23')
# (38,'2-Aug-23')

# (46,'9-Jul-23')
# (66,'31-Jul-23')
# (67,'31-Jul-23')
# (73,'31-Jul-23')
# (75,'31-Jul-23')

In [162]:
mySeed = 24
random_inx_list =list(range(start_inx,end_inx+1))
random_inx_list = [x for x in random_inx_list if x not in skip_inx]
print(f"Allow index is from 0 to {len(random_inx_list)-1}")
random.seed(mySeed)
random.shuffle(random_inx_list)

Allow index is from 0 to 10

In [163]:
chosen_inx = random_inx_list[0]

In [164]:
script.head()

,index,audio_path,French,English,Topic,level
0,1.0,C:\C_Video_Python\Learn French\100 questions e...,"Aujourd'hui, j'ai envie\n de vous raconter que...",I want to tell you\r about something today.,None,None
1,2.0,C:\C_Video_Python\Learn French\100 questions e...,"Souvent, je prends des nouvelles de ma\r famil...",I often check up on my family\r by calling the...,None,None
2,3.0,C:\C_Video_Python\Learn French\100 questions e...,"Et depuis quelque temps, j'essaie de\r changer...","And for some time now, I've been trying\r to c...",None,None
3,4.0,C:\C_Video_Python\Learn French\100 questions e...,"Avant,\r si j'appelais mon frère ou mes cousins,","When I used to call\r my brother or my cousins,",None,None
4,5.0,C:\C_Video_Python\Learn French\100 questions e...,je leur demandais seulement :\r « Ça va ? ». O...,"I'd just ask them: ""Are\r you all right? Or,",None,None

# Set up per audio

In [165]:
chosen_inx

254

In [166]:
print(file_path[chosen_inx])

C:\C_Video_Python\Learn French\100 questions et réponses en français A1 à C1\Question and Answer Part_YoutubeSub\fr_youtube01_254_Ça va sûrement pas être objectif, mais je pense que ma plus grande qualité.wav

In [188]:
########################## run below recurrently ##################################
i = 1
chosen_inx = random_inx_list[i]
# chosen_inx = 137
print(f"Index: {chosen_inx}")
try:
    audio_path = file_path[chosen_inx]
except KeyError as e:
    raise ValueError(f"Please check if index: {random_inx_list[i]} exists in meta file(excel)")
speed_factor = 1
curr_audio = AudioSegment.from_file(file_path[chosen_inx]) 

target_sentence = script.loc[script['index'] == chosen_inx, COL_SENTENCE].values[0].replace('\r','')
translation = script.loc[script['index'] == chosen_inx, COL_TRANSLATION].values[0].replace('\r','')
# play_audio_slower(audio_path, speed_factor)

Index: 257

# Audio

In [189]:
curr_audio

In [186]:
# target_sentence

In [187]:
# translation

# Translation to target

In [180]:
print(translation)

It's probably not going to be objective, but I think that my greatest quality

In [88]:
curr_audio

In [ ]:
###################### show answer
ans = script.loc[chosen_inx-1,'sentence']
print(ans)
################################
text_pred = model_base.transcribe(audio_path,language="pt")['text']
print(text_pred)

text_pred = model_large.transcribe(audio_path,language="pt")['text']
print(text_pred)
playsound(alarm_path)